function Get-ADDSInfo {

    # Collect Forest-level information
    $adforest = Get-ADForest
    $partitions = Get-ADForest | Select-Object -ExpandProperty ApplicationPartitions
    $forestdnspart = $partitions[1]
    $forestdns = "LDAP://CN=Infrastructure,$forestdnspart"
    
    Write-Output "Active Directory Forest configuration"
    $adforest | Select-Object Name,ForestMode,RootDomain,SchemaMaster,DomainNamingMaster | Format-List
    Write-Output "Forest DNS Zone Master"
    [adsi]$forestdns | Select-Object -ExpandProperty fsmoRoleOwner | 
    Write-Output `n
    Write-Output "UPN Suffixes"
    $adforest | Select-Object -ExpandProperty UPNSuffixes | Format-List
    Write-Output `n
    Write-Output "Active Directory Recycle Bin configuration"
    Get-ADOptionalFeature -Identity "Recycle Bin Feature" | Select-Object 
    Write-Output `n
    Write-Output "All trusted domains"
    Get-ADTrust -Filter * 

    # Collect Domain-level information
    $domains = Get-ADForest | Select-Object -ExpandProperty Domains
    foreach ($domain in $domains){
        $dn = Get-ADDomain -Identity $domain | Select-Object -ExpandProperty DistinguishedName
        Write-Output "Domain information: $domain"
        Get-ADDomain -Identity $domain | Select-Object DistinguishedName,NetBIOSName,DomainMode,PDCEmulator,RIDMaster,InfrastructureMaster
        Write-Output `n
        Write-Output "Domain Controllers"
        Get-ADDomainController -Filter * -DomainName $domain | Select-Object ExpandProperty HostName
        Write-Output `n
        Write-Output "Subordinate references"
        Get-ADDomain -Identity $domain | Select-Object -ExpandProperty SubordinateReferences
        Write-Output `n
        Write-Output "Domain DNS Zone Master"
        $domaindns = "LDAP://CN=Infrastructure,DC=DomainDnsZones,$dn"
        [adsi]$domaindns | Select-Object -ExpandProperty fsmoRoleOwner | Format-List *
    }

    # Collect site replication subnets
    Write-Output `n
    Write-Output "AD Replication Sites and Subnets"
    Get-AdReplicationSubnet -Filter * | Select-Object Site,Name | Sort-Object Site | Format-Table -AutoSize
    Write-Output `n
    Write-Output "AD Replication Connections"
    Get-ADReplicationConnection -Filter * | Select-Object ReplicateFromDirectoryServer,ReplicateToDirectoryServer,AutoGenerated | Sort-Object ReplicateFromDirectoryServer | Format-Table -AutoSize
}